vim.cmd('packadd paq-nvim')
local paq = require'paq-nvim'.paq

paq{'savq/paq-nvim', opt = true}

paq 'RishabhRD/nvim-lsputils'
paq 'RishabhRD/popfix'
paq 'arcticicestudio/nord-vim'
paq 'famiu/nvim-reload'
paq 'folke/lsp-colors.nvim'
paq 'folke/lsp-trouble.nvim'
paq 'folke/which-key.nvim'
paq 'hoob3rt/lualine.nvim'
paq 'jiangmiao/auto-pairs'
paq 'kyazdani42/nvim-tree.lua'
paq 'kyazdani42/nvim-web-devicons'
paq 'mg979/vim-visual-multi'
paq 'neovim/nvim-lspconfig'
paq 'norcalli/nvim-colorizer.lua'
paq 'nvim-lua/completion-nvim'
paq 'nvim-lua/lsp_extensions.nvim'
paq 'nvim-lua/plenary.nvim'
paq 'nvim-lua/popup.nvim'
paq 'nvim-telescope/telescope.nvim'
paq 'psliwka/vim-smoothie'
paq 'ryanoasis/vim-devicons'
paq 'voldikss/vim-floaterm'

require'plugins/colorizer'
require'plugins/floaterm'
require'plugins/nvim-lsputils'
require'plugins/nvimtree'
require'plugins/telescope'
--require'plugins/trouble'
require'plugins/whichkey'
